### PR TITLE
added test case for extraHeaders (client)

### PR DESCRIPTION
**Pull request by adrai**
https://github.com/Automattic/engine.io-client/pull/379

### CODE REVIEW

**Comment by rauchg** [comment]
In this case you're sending the headers over the socket. What you want to do is introspect the `request` of the `socket` and check its `headers`.

**Comment by adrai** [comment]
uups sorry.... this was too fast... wait a sec...

**Comment by adrai** [comment]
ok?

**Comment by rauchg** [comment]
You have to rebase this @adrai – Thanks for your contributions & follow-ups 👊

**Comment by adrai** [comment]
done
- And thanks to you ;-)

**Comment by rauchg** [comment]
This is great!

**Pull request merged**
