### PR TITLE
ws v0.7.2

### PR DESCRIPTION
**Pull request by johanneswuerbach**
iojs 2.x support

Fixes https://github.com/Automattic/socket.io/issues/2057

### CODE REVIEW

**Comment by shinnn** [comment]
+1

**Comment by chapgaga** [comment]
@johanneswuerbach what ws means?

**Comment by shinnn** [comment]
@chapgaga https://github.com/Automattic/engine.io/blob/860af4dc0b47e55a623e7e56ce097ba4b610264b/package.json#L17

**Comment by chapgaga** [comment]
@shinnn is engine.io websocket implementation for socket.io?

**Comment by nkzawa** [comment]
:+1:

**Pull request merged**
